CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "CompanyNit" character varying(20),
    "CompanyName" character varying(150),
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AdminDrivers" (
    "AdminId" integer NOT NULL,
    "DriverId" integer NOT NULL,
    "LinkedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AdminDrivers" PRIMARY KEY ("AdminId", "DriverId"),
    CONSTRAINT "FK_AdminDrivers_AspNetUsers_AdminId" FOREIGN KEY ("AdminId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AdminDrivers_AspNetUsers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "Address" text NOT NULL,
    "Status" integer NOT NULL,
    "RequiresEvidence" boolean NOT NULL,
    "AdminId" integer,
    "DriverId" integer,
    "EvidenceUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DeliveredAt" timestamp with time zone,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_AspNetUsers_AdminId" FOREIGN KEY ("AdminId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_AspNetUsers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
);

CREATE TABLE "SavedRoutes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DriverId" integer NOT NULL,
    "RouteName" character varying(100) NOT NULL,
    "OrderIds" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "LastUsedDate" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    "OptimizationScore" integer,
    CONSTRAINT "PK_SavedRoutes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SavedRoutes_AspNetUsers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AdminDrivers_DriverId" ON "AdminDrivers" ("DriverId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_Orders_AdminId" ON "Orders" ("AdminId");

CREATE INDEX "IX_Orders_DriverId" ON "Orders" ("DriverId");

CREATE INDEX "IX_SavedRoutes_DriverId" ON "SavedRoutes" ("DriverId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207192502_InitialCreate', '8.0.4');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251212015717_InitialCreate2', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "SavedRoutes" ADD "AssignedByAdminId" integer;

CREATE INDEX "IX_SavedRoutes_AssignedByAdminId" ON "SavedRoutes" ("AssignedByAdminId");

ALTER TABLE "SavedRoutes" ADD CONSTRAINT "FK_SavedRoutes_AspNetUsers_AssignedByAdminId" FOREIGN KEY ("AssignedByAdminId") REFERENCES "AspNetUsers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214201705_AddAssignedByAdminToSavedRoute', '8.0.4');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214232116_UpdateOrderSchema', '8.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "SavedRoutes" ADD "CompletedDate" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216225720_AddCompletedDateToSavedRoute', '8.0.4');

COMMIT;

